#Spring项目名
spring:
  application:
    name: dubbo_provider


dubbo:
  application:
    name: dubbo_provider
    id: dubbo_provider
  #服务注册的地址
  registry:
    protocol: zookeeper
    address: 'zookeeper://127.0.0.1:2181'
  protocol:
    name: dubbo
    port: 23456
  #扫描注解包通过该设置将服务注册到zookeeper
  scan:
    base-packages: com.smart.provider.service

demo:
  service:
    version: 1.0.0
